### ISSUE TITLE
releases missing

### ISSUE THREAD

**Issue by stevewallcgi** [cloudfoundry-community/minio-boshrelease#1]
I'm trying to deploy a release and it doesn't look like the releases directory is there. Am I missing something?

$ git clone https://github.com/cloudfoundry-community/minio-boshrelease.git
$ cd minio-boshrelease
$ bosh upload release releases/minio/minio-1.yml
Release file doesn't exist
$ ls
config  jobs  LICENSE.md  packages  Rakefile  README.md  src  templates

**Comment by jhunt** [comment]
I do not believe that we have actually cut a release yet.  The README is supplied by bosh-gen, so it's a bit misleading until we do that first release.

@mrferris may know more

**Comment by stevewallcgi** [comment]
I had to do a "bosh create release". Which created a dev_releases directory. I'm working from there. I did notice the templates/make_manifest doesn't have an openstack option. Although the README.md has a reference to it.

**Comment by shinji62** [comment]
@stevewallecs I create a distributed version for minio server https://github.com/shinji62/minio-dist-boshrelease if you want to give a try.

**Comment by stevewallcgi** [comment]
Thanks @shinji62! I'll keep it in mind.

**Comment by drnic** [comment]
I'll close this issue. And I'll move the repo into the attic so as to help ppl find https://github.com/shinji62/minio-dist-boshrelease instead.
